import type { Prediction, Team } from "./types";

const teams: Record<string, Team> = {
  MEX: { id: "mex", code: "MEX", name: "Mexico", nameZh: "墨西哥", flag: "🇲🇽", fifaRank: 15, squadValueM: 190, form: ["W", "W", "D", "W", "W"] },
  RSA: { id: "rsa", code: "RSA", name: "South Africa", nameZh: "南非", flag: "🇿🇦", fifaRank: 61, squadValueM: 42, form: ["W", "D", "W", "W", "D"] },
  KOR: { id: "kor", code: "KOR", name: "Korea Republic", nameZh: "韩国", flag: "🇰🇷", fifaRank: 22, squadValueM: 145, form: ["W", "W", "D", "L", "W"] },
  CZE: { id: "cze", code: "CZE", name: "Czechia", nameZh: "捷克", flag: "🇨🇿", fifaRank: 44, squadValueM: 165, form: ["W", "D", "W", "D", "L"] },
  CAN: { id: "can", code: "CAN", name: "Canada", nameZh: "加拿大", flag: "🇨🇦", fifaRank: 28, squadValueM: 215, form: ["W", "D", "W", "L", "W"] },
  BIH: { id: "bih", code: "BIH", name: "Bosnia & Herzegovina", nameZh: "波黑", flag: "🇧🇦", fifaRank: 57, squadValueM: 105, form: ["D", "W", "L", "W", "D"] },
  USA: { id: "usa", code: "USA", name: "United States", nameZh: "美国", flag: "🇺🇸", fifaRank: 14, squadValueM: 350, form: ["W", "W", "L", "D", "W"] },
  PAR: { id: "par", code: "PAR", name: "Paraguay", nameZh: "巴拉圭", flag: "🇵🇾", fifaRank: 39, squadValueM: 125, form: ["D", "W", "D", "L", "W"] },
  ARG: { id: "arg", code: "ARG", name: "Argentina", nameZh: "阿根廷", flag: "🇦🇷", fifaRank: 1, squadValueM: 780, form: ["W", "W", "W", "W", "W"] },
  FRA: { id: "fra", code: "FRA", name: "France", nameZh: "法国", flag: "🇫🇷", fifaRank: 2, squadValueM: 1210, form: ["W", "W", "D", "W", "W"] },
};

const shared = {
  stage: "Group stage",
  stageZh: "小组赛",
  status: "upcoming" as const,
  modelVersion: "wc-poisson-1.1.0",
  dataVersion: "schedule-2026-06-11",
  updatedAt: "2026-06-11T00:00:00Z",
};

export const demoPredictions: Prediction[] = [
  {
    ...shared,
    id: "mex-rsa",
    kickoff: "2026-06-11T19:00:00Z",
    venue: "Mexico City Stadium",
    venueZh: "墨西哥城体育场",
    homeTeam: teams.MEX,
    awayTeam: teams.RSA,
    homeWin: 58,
    draw: 25,
    awayWin: 17,
    expectedHomeGoals: 1.72,
    expectedAwayGoals: 0.72,
    likelyScore: "1–0",
    confidence: 79,
    topScores: [
      { home: 1, away: 0, probability: 14.9 },
      { home: 2, away: 0, probability: 12.8 },
      { home: 1, away: 1, probability: 10.7 },
    ],
    factors: [
      { label: "Recent form", labelZh: "近期状态", home: 86, away: 72, note: "Mexico are unbeaten in eight matches", noteZh: "墨西哥最近八场保持不败" },
      { label: "Squad quality", labelZh: "阵容质量", home: 78, away: 59, note: "Player form matters more than market value alone", noteZh: "球员状态的权重高于单独使用身价" },
      { label: "Tournament context", labelZh: "赛事环境", home: 91, away: 67, note: "Mexico receive a measured host advantage", noteZh: "模型给予墨西哥适度主场优势" },
      { label: "Defensive balance", labelZh: "攻防平衡", home: 80, away: 68, note: "South Africa's compact shape limits the margin", noteZh: "南非的紧凑防守降低了大比分概率" },
    ],
    keyPlayers: [
      { name: "Raúl Jiménez", position: "Forward", positionZh: "前锋", teamCode: "MEX", goals: 18, assists: 6, minutes: 2910, rating: 86 },
      { name: "Edson Álvarez", position: "Midfielder", positionZh: "中场", teamCode: "MEX", goals: 4, assists: 4, minutes: 3260, rating: 82 },
      { name: "Teboho Mokoena", position: "Midfielder", positionZh: "中场", teamCode: "RSA", goals: 7, assists: 8, minutes: 3440, rating: 81 },
    ],
  },
  {
    ...shared,
    id: "kor-cze",
    kickoff: "2026-06-12T02:00:00Z",
    venue: "Guadalajara Stadium",
    venueZh: "瓜达拉哈拉体育场",
    homeTeam: teams.KOR,
    awayTeam: teams.CZE,
    homeWin: 43,
    draw: 30,
    awayWin: 27,
    expectedHomeGoals: 1.38,
    expectedAwayGoals: 0.96,
    likelyScore: "1–0",
    confidence: 74,
    topScores: [
      { home: 1, away: 0, probability: 13.3 },
      { home: 1, away: 1, probability: 12.8 },
      { home: 0, away: 0, probability: 9.6 },
    ],
    factors: [
      { label: "Recent form", labelZh: "近期状态", home: 81, away: 73, note: "Korea's transition attack grades higher", noteZh: "韩国的转换进攻评分更高" },
      { label: "Squad quality", labelZh: "阵容质量", home: 77, away: 75, note: "The starting elevens are closely matched", noteZh: "双方预计首发实力接近" },
      { label: "Tournament context", labelZh: "赛事环境", home: 76, away: 71, note: "Neither team receives host advantage", noteZh: "双方均没有东道主加成" },
      { label: "Defensive balance", labelZh: "攻防平衡", home: 80, away: 74, note: "A low-scoring game remains plausible", noteZh: "低比分比赛的可能性较高" },
    ],
    keyPlayers: [
      { name: "Son Heung-min", position: "Forward", positionZh: "前锋", teamCode: "KOR", goals: 24, assists: 13, minutes: 3300, rating: 90 },
      { name: "Patrik Schick", position: "Forward", positionZh: "前锋", teamCode: "CZE", goals: 22, assists: 5, minutes: 2830, rating: 86 },
    ],
  },
  {
    ...shared,
    id: "can-bih",
    kickoff: "2026-06-12T19:00:00Z",
    venue: "Toronto Stadium",
    venueZh: "多伦多体育场",
    homeTeam: teams.CAN,
    awayTeam: teams.BIH,
    homeWin: 49,
    draw: 28,
    awayWin: 23,
    expectedHomeGoals: 1.56,
    expectedAwayGoals: 0.94,
    likelyScore: "1–0",
    confidence: 73,
    topScores: [
      { home: 1, away: 0, probability: 12.8 },
      { home: 1, away: 1, probability: 12.0 },
      { home: 2, away: 0, probability: 10.0 },
    ],
    factors: [
      { label: "Recent form", labelZh: "近期状态", home: 80, away: 69, note: "Canada carry more pace in wide areas", noteZh: "加拿大在边路拥有更强速度" },
      { label: "Squad quality", labelZh: "阵容质量", home: 81, away: 70, note: "Canada's first-choice lineup rates higher", noteZh: "加拿大主力阵容评分更高" },
      { label: "Tournament context", labelZh: "赛事环境", home: 89, away: 68, note: "Home conditions improve Canada's outlook", noteZh: "主场环境提高了加拿大的预测表现" },
      { label: "Defensive balance", labelZh: "攻防平衡", home: 76, away: 72, note: "Bosnia can keep the match compact", noteZh: "波黑有能力保持紧凑阵型" },
    ],
    keyPlayers: [
      { name: "Alphonso Davies", position: "Defender", positionZh: "后卫", teamCode: "CAN", goals: 9, assists: 15, minutes: 3480, rating: 91 },
      { name: "Jonathan David", position: "Forward", positionZh: "前锋", teamCode: "CAN", goals: 30, assists: 8, minutes: 3580, rating: 89 },
    ],
  },
  {
    ...shared,
    id: "usa-par",
    kickoff: "2026-06-13T01:00:00Z",
    venue: "Los Angeles Stadium",
    venueZh: "洛杉矶体育场",
    homeTeam: teams.USA,
    awayTeam: teams.PAR,
    homeWin: 55,
    draw: 27,
    awayWin: 18,
    expectedHomeGoals: 1.88,
    expectedAwayGoals: 0.76,
    likelyScore: "2–0",
    confidence: 77,
    topScores: [
      { home: 2, away: 0, probability: 12.6 },
      { home: 1, away: 0, probability: 12.0 },
      { home: 2, away: 1, probability: 9.6 },
    ],
    factors: [
      { label: "Recent form", labelZh: "近期状态", home: 83, away: 71, note: "USA create more chances per 90 minutes", noteZh: "美国每90分钟创造更多机会" },
      { label: "Squad quality", labelZh: "阵容质量", home: 86, away: 69, note: "USA have greater attacking depth", noteZh: "美国拥有更好的进攻阵容深度" },
      { label: "Tournament context", labelZh: "赛事环境", home: 90, away: 65, note: "Travel and home support favour USA", noteZh: "旅行因素和主场支持有利于美国" },
      { label: "Defensive balance", labelZh: "攻防平衡", home: 82, away: 73, note: "Paraguay still carry set-piece threat", noteZh: "巴拉圭仍有定位球威胁" },
    ],
    keyPlayers: [
      { name: "Christian Pulisic", position: "Forward", positionZh: "前锋", teamCode: "USA", goals: 27, assists: 16, minutes: 3690, rating: 92 },
      { name: "Miguel Almirón", position: "Midfielder", positionZh: "中场", teamCode: "PAR", goals: 10, assists: 9, minutes: 3100, rating: 82 },
    ],
  },
  {
    ...shared,
    id: "review-arg-fra-2022",
    kickoff: "2022-12-18T15:00:00Z",
    stage: "Historical backtest",
    stageZh: "历史回测",
    venue: "Lusail Stadium",
    venueZh: "卢赛尔体育场",
    status: "finished",
    homeTeam: teams.ARG,
    awayTeam: teams.FRA,
    homeWin: 38,
    draw: 30,
    awayWin: 32,
    expectedHomeGoals: 1.46,
    expectedAwayGoals: 1.31,
    likelyScore: "1–1",
    actualScore: "3–3",
    resultNote: "Argentina won 4–2 on penalties",
    resultNoteZh: "阿根廷在点球大战中以4–2获胜",
    confidence: 72,
    topScores: [{ home: 1, away: 1, probability: 12.0 }, { home: 1, away: 0, probability: 9.2 }, { home: 0, away: 1, probability: 8.2 }],
    factors: [],
    keyPlayers: [],
    errorReasons: [
      "The model underestimated late-game tactical changes and substitution impact.",
      "Penalty events and extra-time fatigue create more variance than a standard Poisson assumption.",
      "Elite finishing converted a larger share of chances than the pre-match baseline.",
    ],
    errorReasonsZh: [
      "模型低估了比赛后段战术变化和替补球员的影响。",
      "点球事件与加时赛疲劳带来的波动高于标准泊松假设。",
      "顶级球员的终结效率高于赛前基线。",
    ],
  },
];
